version: '3.8'

services:
  db:
    image: postgres:13  # You can use a specific version, or latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser        # Define the database user
      POSTGRES_PASSWORD: password  # Define the password for the user
      POSTGRES_DB: password      # Define the database name
    ports:
      - "5432:5432"  # Expose PostgreSQL default port
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist data across container restarts

