CREATE TABLE IF NOT EXISTS bulldog.transferEntities (
                                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                 user_id BIGINT NOT NULL,
                                                 from_bank_account_id BIGINT NOT NULL,
                                                 to_bank_account_id BIGINT NOT NULL,
                                                 amount DECIMAL(15, 2) NOT NULL,
    transfer_date DATE NOT NULL,
    from_transaction_id BIGINT,
    to_transaction_id BIGINT,
    description VARCHAR(255),
    status bulldog.transfer_status DEFAULT 'COMPLETED',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                             CONSTRAINT fk_transfers_user_id
                             FOREIGN KEY (user_id)
    REFERENCES bulldog.users(id)
                         ON DELETE CASCADE,
    CONSTRAINT fk_transfers_from_account_id
    FOREIGN KEY (from_bank_account_id)
    REFERENCES bulldog.bank_accounts(id)
                         ON DELETE CASCADE,
    CONSTRAINT fk_transfers_to_account_id
    FOREIGN KEY (to_bank_account_id)
    REFERENCES bulldog.bank_accounts(id)
                         ON DELETE CASCADE,
    CONSTRAINT fk_transfers_from_transaction_id
    FOREIGN KEY (from_transaction_id)
    REFERENCES bulldog.transactionEntities(id)
                         ON DELETE SET NULL,
    CONSTRAINT fk_transfers_to_transaction_id
    FOREIGN KEY (to_transaction_id)
    REFERENCES bulldog.transactionEntities(id)
                         ON DELETE SET NULL,
    CONSTRAINT ck_different_accounts
    CHECK (from_bank_account_id != to_bank_account_id),
    CONSTRAINT ck_positive_transfer_amount
    CHECK (amount > 0)
    );

-- Create indices for transferEntities
CREATE INDEX idx_transfers_user_id ON bulldog.transferEntities(user_id);
CREATE INDEX idx_transfers_from_account ON bulldog.transferEntities(from_bank_account_id);
CREATE INDEX idx_transfers_to_account ON bulldog.transferEntities(to_bank_account_id);
CREATE INDEX idx_transfers_transfer_date ON bulldog.transferEntities(transfer_date DESC);
CREATE INDEX idx_transfers_status ON bulldog.transferEntities(status);


-- Add comments
COMMENT ON TABLE bulldog.transferEntities IS 'Transfer records between userEntity bank accounts';
COMMENT ON COLUMN bulldog.transferEntities.amount IS 'Transfer amount (always positive)';
